### ISSUE TITLE
Regex $ breaks describe match if linebreak

### ISSUE THREAD

**Issue by ryanwinchester** [wgu-it/sage-bot#3]
https://github.com/wgu-it/sage-bot/blob/master/lib/sage/responders/courses.ex#L45

**Comment by Shalmezad** [comment]
May want to add optional whitespace to the end (`\s*`)
`describe (([a-zA-Z]{1,3})(?:\s|-)?([0-9]{1,4}))\s*$`

Try on: https://regex101.com/
